name: PCB things
on:
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '.github/workflows/*.yml'
    branches:
      - main
  push:
    branches:
    - main

jobs:
  kibot:
    uses: ./.github/workflows/kibot.yml
    secrets: inherit
  publish-stable:
    name: "Release Stable"
    permissions:
      contents: write
    uses: ./.github/workflows/module-publish-stable.yml
    secrets: inherit
