name: Publish
run-name: Publish ${{ github.head_ref }}
on:
  workflow_dispatch:
jobs:
  publish:
    name: "Release new version"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Update Version
      run: python3 update-version.py
    - id: cz
      name: Bump version and push to branch
      uses: commitizen-tools/commitizen-action@master
      with:
        github_token: ${{ secrets.RELEASE_PUSH_TOKEN }}
        push: true